apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-cpu-declarative
spec:
  maxReplicas: 6 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster-node-list
  targetCPUUtilizationPercentage: 70 # target CPU utilization